-- FINAL FIX for settings table - Run this entire script in Supabase SQL Editor

-- Step 1: Check if table exists and create proper structure
CREATE TABLE IF NOT EXISTS settings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id UUID NULL,
    key TEXT NOT NULL,
    value TEXT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(key)
);

-- Step 2: Completely disable RLS
ALTER TABLE settings DISABLE ROW LEVEL SECURITY;

-- Step 3: Drop ALL policies (clean slate)
DROP POLICY IF EXISTS "Enable insert for authenticated users" ON settings;
DROP POLICY IF EXISTS "Enable select for authenticated users" ON settings;
DROP POLICY IF EXISTS "Enable update for authenticated users" ON settings;
DROP POLICY IF EXISTS "Enable delete for authenticated users" ON settings;
DROP POLICY IF EXISTS "Enable ALL for authenticated users" ON settings;
DROP POLICY IF EXISTS "Allow all operations" ON settings;
DROP POLICY IF EXISTS "Users can view their own settings" ON settings;
DROP POLICY IF EXISTS "Users can insert their own settings" ON settings;
DROP POLICY IF EXISTS "Users can update their own settings" ON settings;
DROP POLICY IF EXISTS "Users can delete their own settings" ON settings;

-- Step 4: Grant comprehensive permissions
GRANT ALL ON settings TO authenticated;
GRANT ALL ON settings TO service_role;
GRANT SELECT, INSERT, UPDATE ON settings TO anon;

-- Step 5: Clear existing data and insert fresh defaults
DELETE FROM settings;

INSERT INTO settings (key, value) VALUES 
  ('delivery_charge', '50'),
  ('pickup_charge', '30'),
  ('tax_rate', '18'),
  ('minimum_order_amount', '100'),
  ('currency', 'INR'),
  ('support_phone', '+919876543210');

-- Step 6: Verify everything works
SELECT 'Settings table setup completed!' as status;
SELECT * FROM settings ORDER BY key;

-- Step 7: Test update operation
UPDATE settings SET value = '55' WHERE key = 'delivery_charge';
SELECT 'Test update completed' as test_result;
